import { describe, expect, it } from "vitest";
import { ECC_LEVELS, QUIET_ZONE_MODULES, encode, moduleSizeMm, type QrMatrix } from "./encode.js";
import { GOLDEN_MATRICES, GOLDEN_PAYLOADS } from "./goldenMatrices.js";

const rows = (m: QrMatrix): string[] =>
  m.modules.map((row) => row.map((v) => (v ? "1" : "0")).join(""));

describe("encode reproduces the committed golden matrices at every ECC level — A7", () => {
  for (const [name, text] of Object.entries(GOLDEN_PAYLOADS)) {
    for (const ecc of ECC_LEVELS) {
      it(`${name} @ ECC-${ecc}`, () => {
        const golden = GOLDEN_MATRICES[name as keyof typeof GOLDEN_PAYLOADS][ecc];
        const m = encode(text, { ecc });
        expect(m.version).toBe(golden.version);
        expect(m.size).toBe(golden.size);
        expect(rows(m)).toEqual(golden.rows);
      });
    }
  }

  it("is stable across repeated calls, so the mask choice is not a coin flip", () => {
    // uqr picks the mask automatically. "Automatic" is a penalty-score computation over the data
    // rather than a choice, but a label already stuck to a truck cannot be re-encoded, so it is
    // asserted rather than assumed.
    const a = encode(GOLDEN_PAYLOADS.asset, { ecc: "H" });
    const b = encode(GOLDEN_PAYLOADS.asset, { ecc: "H" });
    expect(rows(a)).toEqual(rows(b));
  });
});

/**
 * The goldens above prove STABILITY — the encoder still does what it did. They cannot prove
 * CORRECTNESS, because they were generated by the thing they check. These assertions are the
 * independent half: structural facts a real QR symbol must satisfy, taken from the specification
 * rather than from our own output.
 */
describe("the output is a well-formed QR symbol, checked against the specification", () => {
  const m = encode(GOLDEN_PAYLOADS.asset, { ecc: "H" });

  it("has the size the version demands: 17 + 4 x version", () => {
    for (const ecc of ECC_LEVELS) {
      const encoded = encode(GOLDEN_PAYLOADS.bin, { ecc });
      expect(encoded.size).toBe(17 + 4 * encoded.version);
    }
  });

  it("is square, and every row is the declared width", () => {
    expect(m.modules).toHaveLength(m.size);
    for (const row of m.modules) expect(row).toHaveLength(m.size);
  });

  it("carries the 7x7 finder pattern in the three positioning corners", () => {
    // The specification's finder is a 7x7: dark ring, light ring, 3x3 dark core.
    const finder = [
      "1111111",
      "1000001",
      "1011101",
      "1011101",
      "1011101",
      "1000001",
      "1111111",
    ];
    const at = (top: number, left: number): string[] =>
      Array.from({ length: 7 }, (_, r) =>
        Array.from({ length: 7 }, (_, c) => (m.modules[top + r]?.[left + c] ? "1" : "0")).join(""),
      );
    expect(at(0, 0)).toEqual(finder); // top-left
    expect(at(0, m.size - 7)).toEqual(finder); // top-right
    expect(at(m.size - 7, 0)).toEqual(finder); // bottom-left
  });

  it("has no finder in the fourth corner — that asymmetry is how a scanner finds rotation", () => {
    const bottomRight = Array.from({ length: 7 }, (_, r) =>
      Array.from({ length: 7 }, (_, c) =>
        m.modules[m.size - 7 + r]?.[m.size - 7 + c] ? "1" : "0",
      ).join(""),
    );
    expect(bottomRight[0]).not.toBe("1111111");
  });

  it("carries the alternating timing patterns on row 6 and column 6", () => {
    // Between the finders, row 6 and column 6 alternate dark/light starting dark at module 8.
    for (let i = 8; i < m.size - 8; i += 1) {
      const expectedDark = i % 2 === 0;
      expect(m.modules[6]?.[i]).toBe(expectedDark);
      expect(m.modules[i]?.[6]).toBe(expectedDark);
    }
  });

  it("changes completely when one character of the payload changes", () => {
    // A fixture too uniform to discriminate is how ten assertions pass while proving nothing.
    const other = encode("SIL1:AST:7K3M9Q", { ecc: "H" });
    expect(rows(other)).not.toEqual(rows(m));
  });

  it("needs at least as large a symbol at a higher correction level", () => {
    const l = encode(GOLDEN_PAYLOADS.asset, { ecc: "L" });
    const h = encode(GOLDEN_PAYLOADS.asset, { ecc: "H" });
    expect(h.version).toBeGreaterThanOrEqual(l.version);
  });
});

describe("the payload fits the label, with room to spare", () => {
  it("encodes both real tags inside the version-4 budget §2.4 set", () => {
    for (const text of Object.values(GOLDEN_PAYLOADS)) {
      expect(encode(text, { ecc: "H" }).version).toBeLessThanOrEqual(4);
    }
  });

  it("stays well clear of the ~0.4 mm phone-camera floor on a 1-inch label", () => {
    // Research §4.7's "~0.69 mm at 1 inch" is a version-3 symbol measured WITH its quiet zone,
    // which is the convention moduleSizeMm reproduces.
    const mm = moduleSizeMm(encode(GOLDEN_PAYLOADS.asset, { ecc: "H" }), 25.4);
    expect(mm).toBeGreaterThan(0.4);
    expect(mm).toBeCloseTo(25.4 / (25 + QUIET_ZONE_MODULES * 2), 3);
  });
});
