import { DQ_KIND_LABELS, type DqFileItem, type DqItemState } from "@silvicom/shared";
import type { BinderCarrier, BinderDocumentRef, DriverBinderData } from "./gather.js";
import {
  body,
  CONTENT_WIDTH,
  DANGER,
  field,
  heading,
  INK,
  MARGIN,
  MUTED,
  muted,
  newDrawing,
  OK,
  rule,
  table,
  title,
  WARN,
  type Cell,
} from "./pdfDraw.js";

/**
 * The pages the binder AUTHORS (DQ-BINDER-PLAN §3). The scans are copied in by `merge.ts`.
 *
 * Every one of these pages exists to make the copied pages usable: the checklist is the index the
 * auditor works from, the separators say what each scan is meant to prove, and the history answers
 * "what did the medical card say on 3 March" — which a folder of PDFs cannot.
 */

export interface BinderContext {
  carrier: BinderCarrier;
  asAt: string;
  generatedAt: string;
  generatedBy: string;
  exportId: string;
}

const STATE_LABEL: Record<DqItemState, string> = {
  current: "on file",
  expiring: "due soon",
  expired: "expired",
  missing: "missing",
};
const STATE_COLOR: Record<DqItemState, string> = {
  current: OK,
  expiring: WARN,
  expired: DANGER,
  missing: DANGER,
};

const dash = (v: string | null | undefined): string => (v && v.trim() ? v : "—");
const stamp = (iso: string): string => iso.slice(0, 19).replace("T", " ") + " UTC";

/** D-BD5 — the same three numbers on the cover, the checklist and the ledger row. */
export function completeness(data: DriverBinderData): string {
  const c = data.file.counts;
  const total = data.file.items.length;
  return `${total} requirements · ${c.current + c.expiring} on file · ${c.expired} expired · ${c.missing} never recorded`;
}

const CARRIER_LINE = (carrier: BinderCarrier): string =>
  `${carrier.name} · USDOT ${carrier.dotNumber ?? "not recorded"}`;

/**
 * The master cover (D-BD2). One binder, one cover, listing the sample the auditor named — in the
 * order they named it, so it can be checked off against their own list without re-finding anybody.
 */
export async function renderMasterCover(
  drivers: DriverBinderData[],
  ctx: BinderContext,
  missingIds: string[],
): Promise<Buffer> {
  const { doc, done } = newDrawing("Driver qualification files");

  title(doc, "Driver qualification files");
  doc.moveDown(0.3);
  muted(doc, `49 CFR §391.51. Prepared from ${CARRIER_LINE(ctx.carrier)}.`);
  doc.moveDown(0.8);

  field(doc, "Carrier", ctx.carrier.name);
  field(doc, "USDOT number", ctx.carrier.dotNumber ?? "Not recorded");
  field(doc, "Drivers in this binder", String(drivers.length));
  field(doc, "File as it stood on", ctx.asAt);
  field(doc, "Generated", stamp(ctx.generatedAt));
  field(doc, "Generated by", ctx.generatedBy);
  field(doc, "Export id", ctx.exportId);

  rule(doc);

  heading(doc, "The sample");
  table(
    doc,
    [
      { width: 24, header: "#" },
      { width: 180, header: "Driver" },
      { width: 90, header: "Employee id" },
      { width: CONTENT_WIDTH - 294, header: "Completeness" },
    ],
    drivers.map((d, i): Cell[] => [
      { text: String(i + 1) },
      {
        text: d.driver.name,
        bold: true,
        sub: d.driver.terminationDate ? `Terminated ${d.driver.terminationDate}` : undefined,
      },
      { text: dash(d.driver.employeeId) },
      { text: completeness(d) },
    ]),
  );

  // A request for fifteen drivers that produced fourteen has to say so on the first page. Finding
  // that out by counting is exactly how a binder loses an auditor's trust.
  if (missingIds.length > 0) {
    doc.moveDown(0.6);
    body(
      doc,
      `${missingIds.length} of the ${drivers.length + missingIds.length} drivers requested could not be found in this carrier's roster and are NOT in this binder: ${missingIds.join(", ")}.`,
      DANGER,
    );
  }

  doc.moveDown(0.8);
  rule(doc);
  heading(doc, "How to read this binder");
  body(
    doc,
    "Each driver begins with a cover page and a checklist of every §391.51 requirement, followed by the scans filed against them. Each scan is preceded by a separator page naming the requirement it proves. Nothing has been left out: requirements that are expired or were never recorded are listed by name on the checklist rather than omitted from it.",
  );
  doc.moveDown(0.4);
  body(
    doc,
    "Drug and alcohol test RESULTS are not included. 49 CFR §40.333 keeps the DOT testing file separate and confidential from the driver qualification file; this binder records that a test occurred and on what date, and nothing further.",
  );
  doc.moveDown(0.4);
  muted(
    doc,
    `Every page carries the driver's name, this export id and its page number, so a page separated from the binder can still be tied back to it (§390.32(c)–(d)).`,
  );

  doc.end();
  return done;
}

/** One driver's cover and checklist — the front of their section. */
export async function renderDriverFront(
  data: DriverBinderData,
  ctx: BinderContext,
): Promise<Buffer> {
  const { doc, done } = newDrawing(`Driver qualification file — ${data.driver.name}`);

  title(doc, data.driver.name);
  doc.moveDown(0.3);
  muted(doc, `Driver qualification file · 49 CFR §391.51 · ${CARRIER_LINE(ctx.carrier)}`);
  doc.moveDown(0.8);

  field(doc, "Employee id", dash(data.driver.employeeId));
  field(doc, "Hired", dash(data.driver.hireDate));
  if (data.driver.terminationDate) field(doc, "Employment ended", data.driver.terminationDate);
  field(doc, "Roster status", data.driver.status);
  field(doc, "File as it stood on", ctx.asAt);
  field(doc, "Completeness", completeness(data));

  if (data.file.state === "not_started") {
    doc.moveDown(0.4);
    body(
      doc,
      "Nothing has been filed for this driver. Every requirement below is listed as never recorded — this is an empty file, not a missing binder section.",
      DANGER,
    );
  }

  rule(doc);
  heading(doc, "Checklist — every §391.51 requirement");

  table(
    doc,
    [
      { width: 210, header: "Requirement" },
      { width: 74, header: "Status" },
      { width: 78, header: "Good until" },
      { width: CONTENT_WIDTH - 362, header: "Scan attached" },
    ],
    data.file.items.map((item): Cell[] => [
      { text: item.spec.label, bold: true, sub: item.spec.citation },
      { text: STATE_LABEL[item.state], color: STATE_COLOR[item.state], bold: true },
      {
        text: item.goodUntil ?? (item.state === "missing" ? "—" : "no expiry"),
        sub: item.expiryUnknown ? "no expiry recorded" : undefined,
      },
      { text: item.documentId ? "Yes — follows this checklist" : "No scan on file" },
    ]),
  );

  doc.end();
  return done;
}

/**
 * The separator that precedes a scan. It is the page that makes a copied PDF mean something: without
 * it, page 34 of the binder is an unlabelled photocopy of a card.
 */
export async function renderSeparator(
  data: DriverBinderData,
  label: string,
  citation: string,
  ref: BinderDocumentRef,
  goodUntil: string | null,
  ctx: BinderContext,
): Promise<Buffer> {
  const { doc, done } = newDrawing(label);

  doc.moveDown(6);
  muted(doc, data.driver.name.toUpperCase());
  doc.moveDown(0.2);
  title(doc, label);
  doc.moveDown(0.3);
  muted(doc, citation);
  doc.moveDown(1.2);

  field(doc, "Good until", goodUntil ?? "No expiry recorded");
  field(doc, "Filed", stamp(ref.createdAt));
  field(doc, "Document id", ref.id);
  field(doc, "SHA-256", ref.sha256);

  doc.moveDown(1);
  body(doc, "The page or pages that follow are the scan filed as evidence for this requirement.");
  doc.moveDown(0.3);
  muted(
    doc,
    `Reproduced from ${ctx.carrier.name}'s compliance record store. The SHA-256 above is the digest recorded when the scan was filed, so this copy can be checked against the original.`,
  );

  doc.end();
  return done;
}

/**
 * A page that stands where a scan could not. Never a silent gap: the auditor is told the document
 * exists, what it is, and why its pages are absent — which is recoverable, whereas a quiet omission
 * discovered later is not.
 */
export async function renderUnreadable(
  data: DriverBinderData,
  label: string,
  ref: BinderDocumentRef,
  reason: string,
): Promise<Buffer> {
  const { doc, done } = newDrawing(label);
  doc.moveDown(6);
  muted(doc, data.driver.name.toUpperCase());
  doc.moveDown(0.2);
  title(doc, label);
  doc.moveDown(1);
  body(doc, "This scan is on file but could not be reproduced into this binder.", DANGER);
  doc.moveDown(0.5);
  field(doc, "Document id", ref.id);
  field(doc, "Filed", stamp(ref.createdAt));
  field(doc, "Format", ref.contentType);
  field(doc, "SHA-256", ref.sha256);
  doc.moveDown(0.6);
  muted(doc, `Reason: ${reason}`);
  doc.moveDown(0.4);
  muted(doc, "The original is intact in the record store and can be supplied on its own.");
  doc.end();
  return done;
}

/** The back of a driver's section: the supersede chain, then the §391.51 event log. */
export async function renderDriverBack(data: DriverBinderData): Promise<Buffer> {
  const { doc, done } = newDrawing(`Certification history — ${data.driver.name}`);

  title(doc, "Certification history");
  doc.moveDown(0.3);
  muted(
    doc,
    `${data.driver.name} · every certification ever filed, current and superseded, so what was on file on any past date is answerable.`,
  );
  doc.moveDown(0.6);

  if (data.certHistory.length === 0) {
    body(doc, "No certifications have ever been filed for this driver.");
  } else {
    table(
      doc,
      [
        { width: 168, header: "Certification" },
        { width: 96, header: "Identifier" },
        { width: 78, header: "Effective" },
        { width: 78, header: "Expires" },
        { width: CONTENT_WIDTH - 420, header: "Standing" },
      ],
      data.certHistory.map((c): Cell[] => [
        {
          text: DQ_KIND_LABELS[c.kind] ?? c.kind,
          bold: true,
          sub:
            [c.qualifier ? `endorsement ${c.qualifier}` : null, c.trainingType?.replace(/_/g, " ")]
              .filter(Boolean)
              .join(" · ") || undefined,
        },
        { text: dash(c.identifier), sub: c.issuingAuthority ?? undefined },
        { text: c.effectiveFrom },
        { text: dash(c.expiresAt) },
        {
          text: c.current ? "Current" : "Superseded",
          color: c.current ? OK : MUTED,
          sub: c.supersededAt ? `on ${c.supersededAt.slice(0, 10)}` : undefined,
        },
      ]),
    );
  }

  doc.addPage();
  title(doc, "Qualification event log");
  doc.moveDown(0.3);
  muted(
    doc,
    `${data.driver.name} · §391.51 events, most recent first. Append-only: a correction is a new entry, never an edit.`,
  );
  doc.moveDown(0.6);

  if (data.events.length === 0) {
    body(doc, "No qualification events have been recorded for this driver.");
  } else {
    table(
      doc,
      [
        { width: 78, header: "Date" },
        { width: 168, header: "Event" },
        { width: 78, header: "Covers until" },
        { width: 100, header: "Performed by" },
        { width: CONTENT_WIDTH - 424, header: "Reference" },
      ],
      data.events.map((e): Cell[] => [
        { text: e.occurredOn },
        { text: DQ_KIND_LABELS[e.kind] ?? e.kind, bold: true },
        { text: dash(e.coversUntil) },
        { text: dash(e.performedBy) },
        { text: dash(e.reference) },
      ]),
    );
  }

  const hasTest = data.events.some((e) => e.kind === "drug_test" || e.kind === "alcohol_test");
  if (hasTest) {
    doc.moveDown(0.8);
    doc
      .fillColor(INK)
      .font("Helvetica")
      .fontSize(9)
      .text(
        "Drug and alcohol test entries above record that a test occurred and on what date. Results are held in the DOT testing file, which 49 CFR §40.333 keeps separate and confidential from the driver qualification file, and are not reproduced here.",
        MARGIN,
        doc.y,
        { width: CONTENT_WIDTH },
      );
  }

  doc.end();
  return done;
}

/**
 * The cover of a single-document export (D-BD10). Not a separator — a covering page, addressed
 * outward, that makes the scan behind it verifiable on its own.
 */
export async function renderStampedDocument(
  data: DriverBinderData,
  item: DqFileItem,
  ref: BinderDocumentRef,
  ctx: BinderContext,
): Promise<Buffer> {
  const { doc, done } = newDrawing(`${item.spec.label} — ${data.driver.name}`);

  title(doc, item.spec.label);
  doc.moveDown(0.3);
  muted(
    doc,
    `${item.spec.citation} · issued from the driver qualification file of ${CARRIER_LINE(ctx.carrier)}`,
  );
  doc.moveDown(1);

  field(doc, "Driver", data.driver.name);
  field(doc, "Employee id", dash(data.driver.employeeId));
  field(doc, "Status on this date", STATE_LABEL[item.state]);
  field(doc, "Good until", item.goodUntil ?? "No expiry recorded");
  field(doc, "Verified as at", ctx.asAt);

  rule(doc);

  field(doc, "Released by", ctx.generatedBy);
  field(doc, "Released", stamp(ctx.generatedAt));
  field(doc, "Export id", ctx.exportId);
  field(doc, "Document id", ref.id);
  field(doc, "SHA-256", ref.sha256);

  doc.moveDown(1);
  if (item.state === "expired" || item.state === "expiring") {
    body(
      doc,
      item.state === "expired"
        ? "This credential had EXPIRED as at the date above. It is released as a record of what is on file, not as evidence of a current qualification."
        : "This credential expires within thirty days of the date above.",
      item.state === "expired" ? DANGER : WARN,
    );
    doc.moveDown(0.5);
  }
  body(
    doc,
    "The page or pages that follow are the scan held on file for this requirement. Every page carries the export id above, so this document can be traced back to the release recorded against it.",
  );
  doc.moveDown(0.4);
  muted(
    doc,
    "Released for verification of this requirement only. It is part of a driver qualification file retained under 49 CFR §391.51 and contains personal information.",
  );

  doc.end();
  return done;
}
