/**
 * Expo config plugin — sign Android release builds with OUR keystore (ship-pipeline plan D1.2).
 *
 * `apps/driver/android` is generated by `expo prebuild` and is not tracked, so the release build
 * type comes back signed with the DEBUG keystore every time — Expo's template even says so in a
 * comment. A debug-signed APK installs, which is exactly why this is dangerous: the fleet would be
 * running builds signed with a publicly known key, and the first properly signed release would then
 * refuse to install over them (Android rejects a signature change on upgrade).
 *
 * This appends a second `android { }` block rather than editing the template's existing one.
 * Gradle's android extension is configurable more than once, so appending is idempotent and cannot
 * be broken by an upstream template reflow — regex surgery inside the generated block would be.
 *
 * Inert unless ANDROID_KEYSTORE_PATH is set, so `expo run:android` on a laptop is untouched and
 * still uses the debug keystore. CI sets all four variables; nothing is ever read from a file in
 * the repository.
 */
const { withAppBuildGradle } = require("expo/config-plugins");

const MARKER = "// ── FuelGuard release signing (plugins/withReleaseSigning.js) ──";

const BLOCK = `
${MARKER}
android {
    signingConfigs {
        release {
            storeFile file(System.getenv("ANDROID_KEYSTORE_PATH"))
            storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
            keyAlias System.getenv("ANDROID_KEY_ALIAS")
            keyPassword System.getenv("ANDROID_KEY_PASSWORD")
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}
`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (!process.env.ANDROID_KEYSTORE_PATH) return cfg; // local dev — leave the debug keystore alone
    if (cfg.modResults.contents.includes(MARKER)) return cfg;
    cfg.modResults.contents += BLOCK;
    return cfg;
  });
};
