import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { decodePng } from "../fixtures/png.mjs";
import { BUNDLED_DEFAULT_CONFIG } from "../src/config.js";
import { computeMetrics } from "../src/metrics.js";

/**
 * `expected.json` still describes what the reference actually computes (Step 2.1, D-SCAN9).
 *
 * ── WHY THIS MATTERS MORE THAN IT LOOKS ───────────────────────────────────────────────────────
 * That file is the contract the Swift and Kotlin implementations will be held to in Phase 3, and the
 * units every threshold derived in Phase 5.2 will be expressed in. It is generated by a script that
 * CI never runs — deliberately, because regeneration needs a Node that strips types while
 * verification only needs vitest. So the failure mode is precise: someone changes the metric, does
 * not regenerate, and the baseline silently describes arithmetic that no longer exists. Two native
 * suites then pass against a fiction.
 *
 * This recomputes from the PNGs rather than importing the generator, so the check is an independent
 * path to the same numbers rather than the generator agreeing with itself.
 */

const FIXTURES = fileURLToPath(new URL("../fixtures/", import.meta.url));

interface ExpectedFixture {
  name: string;
  pixelSha256: string;
  width: number;
  height: number;
  metrics: {
    longEdgePx: number;
    analysisLongEdgePx: number;
    blurVariance: number;
    glareFraction: number;
    brightnessMean: number;
    contrastRms: number;
    shadowRange: number;
  };
}

const expected = JSON.parse(readFileSync(join(FIXTURES, "expected.json"), "utf8")) as {
  metricsVersion: string;
  analysisLongEdgePx: number;
  corpusVersion: string;
  tolerance: {
    blurVarianceRelative: number;
    fractionAbsolute: number;
    baselineDecimals: { blurVariance: number; fraction: number };
  };
  fixtures: ExpectedFixture[];
};

const manifest = JSON.parse(readFileSync(join(FIXTURES, "manifest.json"), "utf8")) as {
  corpusVersion: string;
  fixtures: Array<{ name: string; file: string; pixelSha256: string }>;
};

describe("the parity baseline", () => {
  it("covers every fixture in the corpus, and no others", () => {
    // A fixture added without regenerating would never be measured by the native suites, and one
    // removed would leave them comparing against a file that is no longer there.
    expect(expected.fixtures.map((f) => f.name).sort()).toEqual(manifest.fixtures.map((f) => f.name).sort());
    expect(expected.corpusVersion).toBe(manifest.corpusVersion);
  });

  it("was computed at the analysis scale the signed config declares", () => {
    expect(expected.analysisLongEdgePx).toBe(BUNDLED_DEFAULT_CONFIG.analysis.longEdgePx);
  });

  it("names the pixels it measured, so a native suite reads one file rather than two", () => {
    const byName = new Map(manifest.fixtures.map((f) => [f.name, f]));
    for (const f of expected.fixtures) {
      expect(f.pixelSha256, `${f.name} digest`).toBe(byName.get(f.name)!.pixelSha256);
    }
  });

  it("still matches what the reference computes for every fixture", () => {
    const byName = new Map(manifest.fixtures.map((f) => [f.name, f]));
    for (const f of expected.fixtures) {
      const { width, height, rgb } = decodePng(readFileSync(join(FIXTURES, byName.get(f.name)!.file)));
      const actual = computeMetrics(rgb, width, height, expected.analysisLongEdgePx);

      expect(actual.longEdgePx, `${f.name} longEdgePx`).toBe(f.metrics.longEdgePx);
      expect(actual.analysisLongEdgePx, `${f.name} analysisLongEdgePx`).toBe(f.metrics.analysisLongEdgePx);
      // The committed values are rounded for a stable diff, so the comparison allows the last place
      // and nothing more — this is a drift check, not a tolerance for a different implementation.
      expect(actual.blurVariance, `${f.name} blurVariance`).toBeCloseTo(f.metrics.blurVariance, 3);
      expect(actual.glareFraction, `${f.name} glareFraction`).toBeCloseTo(f.metrics.glareFraction, 5);
      expect(actual.brightnessMean, `${f.name} brightnessMean`).toBeCloseTo(f.metrics.brightnessMean, 5);
      expect(actual.contrastRms, `${f.name} contrastRms`).toBeCloseTo(f.metrics.contrastRms, 5);
      expect(actual.shadowRange, `${f.name} shadowRange`).toBeCloseTo(f.metrics.shadowRange, 5);
    }
  });

  it("carries the tolerances the native suites must use, in one place", () => {
    // Phase 3's XCTest and JUnit read these rather than each choosing a number under deadline
    // pressure. They are a starting point derived from cross-language rounding, NOT a measurement —
    // the plan's §6 Q3 says so, and the correct response to a miss is to find out why.
    expect(expected.tolerance.blurVarianceRelative).toBeGreaterThan(0);
    expect(expected.tolerance.fractionAbsolute).toBeGreaterThan(0);
  });

  it("records a metrics version, so a native suite pinned to older arithmetic fails loudly", () => {
    expect(expected.metricsVersion).toMatch(/^scanner-metrics-\d+$/);
  });

  it("rounds every committed value to the number of places it says it does", () => {
    // `baselineDecimals` is not decoration: the iOS harness reads it to work out how much of a
    // deviation this file's own rounding can account for, and then holds Swift to the REMAINDER.
    // Measured on 2026-09-07, that strict bound is what catches a definition error the loose
    // tolerances above cannot see — a Rec.709 coefficient off by one, and a truncating downscale,
    // both passed at ±2% / ±0.002. So a value carrying more places than declared would hand the
    // native side a bound smaller than the rounding it is meant to explain, and it would fail for a
    // reason that has nothing to do with its arithmetic.
    const places = (value: number) => {
      const text = String(value);
      const dot = text.indexOf(".");
      return dot < 0 ? 0 : text.length - dot - 1;
    };
    const { blurVariance, fraction } = expected.tolerance.baselineDecimals;
    for (const f of expected.fixtures) {
      expect(places(f.metrics.blurVariance), `${f.name} blurVariance places`).toBeLessThanOrEqual(blurVariance);
      for (const metric of ["glareFraction", "brightnessMean", "contrastRms", "shadowRange"] as const) {
        expect(places(f.metrics[metric]), `${f.name} ${metric} places`).toBeLessThanOrEqual(fraction);
      }
    }
  });
});
