#!/usr/bin/env node
/**
 * The scanner fixture corpus — 24 synthetic document pages (SCANNER-UPGRADE-PLAN.md, Step 0.3).
 *
 * ── WHAT THIS IS FOR ──────────────────────────────────────────────────────────────────────────
 * One metric definition (D-SCAN1..5) will shortly have three implementations: the TypeScript
 * reference in `src/metrics.ts`, a Swift one, and a Kotlin one. Nothing today compares any two of
 * them, and the audit that produced this plan found exactly what happens when nothing does — the
 * client and server thresholds were declared "aligned" and were measuring different images.
 *
 * This corpus is how the three are held together: every implementation reads the same files and must
 * produce the same numbers. That is also why the fixtures are SYNTHETIC and generated by committed
 * code rather than photographed. A photograph is evidence of one moment that nobody can re-derive; a
 * generator is a definition a reviewer can read, argue with, and regenerate. Real truck-cab
 * photographs are still wanted and are added beside these by Step 0.1 — they are the ground truth for
 * THRESHOLDS (Step 5.2). These are the ground truth for PARITY, which is a different job.
 *
 * ── WHY THE MANIFEST DIGESTS PIXELS, NOT FILES ────────────────────────────────────────────────
 * `deflate` output is not guaranteed identical across zlib versions, so a byte-comparison of the PNGs
 * could go red on a Node upgrade while every pixel was unchanged — a false alarm that teaches people
 * to ignore the check. What must not drift is the PIXELS, so `manifest.json` records a sha256 over
 * the raw RGB of each fixture and `--check` compares that. `tests/fixtures.test.ts` decodes the
 * committed files and holds them to the same digests, which is what makes an edited or truncated PNG
 * on disk fail rather than pass quietly.
 *
 * ── DIMENSIONS ARE NOT ARBITRARY ──────────────────────────────────────────────────────────────
 * 1240 x 1654 (A4 at ~150 dpi) puts the long edge at 1654: above the 1200 px resolution floor these
 * pages must clear, and above the 1024 px analysis scale (D-SCAN1) so every fixture exercises the
 * real downscale path rather than the "already small enough" branch that skips it.
 *
 * Usage:  node fixtures/generate.mjs           write the corpus + manifest
 *         node fixtures/generate.mjs --check   regenerate in memory; non-zero exit on any drift
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { encodePng } from "./png.mjs";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const PORTRAIT = { width: 1240, height: 1654 };
const LANDSCAPE = { width: 1654, height: 1240 };

// ── deterministic randomness ────────────────────────────────────────────────────────────────────
// Seeded per fixture so a page's ink jitter is reproducible, and so two fixtures that differ only by
// an effect differ ONLY by that effect. mulberry32: small, well-distributed, and easy to restate.
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const clamp = (v) => (v < 0 ? 0 : v > 255 ? 255 : Math.round(v));

// ── canvas ──────────────────────────────────────────────────────────────────────────────────────
function canvas(width, height, fill) {
  const rgb = Buffer.alloc(width * height * 3);
  for (let i = 0; i < rgb.length; i += 3) {
    rgb[i] = fill[0];
    rgb[i + 1] = fill[1];
    rgb[i + 2] = fill[2];
  }
  return { width, height, rgb };
}

function setPixel(c, x, y, colour) {
  if (x < 0 || y < 0 || x >= c.width || y >= c.height) return;
  const i = (y * c.width + x) * 3;
  c.rgb[i] = clamp(colour[0]);
  c.rgb[i + 1] = clamp(colour[1]);
  c.rgb[i + 2] = clamp(colour[2]);
}

function fillRect(c, x0, y0, w, h, colour) {
  for (let y = y0; y < y0 + h; y++) for (let x = x0; x < x0 + w; x++) setPixel(c, x, y, colour);
}

/** Per-pixel transform over the whole canvas: `(r,g,b,x,y) -> [r,g,b]`. */
function mapPixels(c, fn) {
  for (let y = 0; y < c.height; y++) {
    for (let x = 0; x < c.width; x++) {
      const i = (y * c.width + x) * 3;
      const out = fn(c.rgb[i], c.rgb[i + 1], c.rgb[i + 2], x, y);
      c.rgb[i] = clamp(out[0]);
      c.rgb[i + 1] = clamp(out[1]);
      c.rgb[i + 2] = clamp(out[2]);
    }
  }
  return c;
}

// ── the page ────────────────────────────────────────────────────────────────────────────────────
const PAPER = [232, 231, 226]; // off-white, faintly warm — real paper is never 255
const INK = [58, 57, 60];
const STAMP_RED = [176, 42, 38];
const PEN_BLUE = [36, 62, 148];

/**
 * A document page on a surface. `density` controls how much of the page carries text, which is the
 * axis the OCR legibility signal and the contrast metric are most sensitive to.
 */
function drawPage(c, { surface, density, marks, seed }) {
  const random = rng(seed);
  mapPixels(c, () => surface);

  const margin = Math.round(Math.min(c.width, c.height) * 0.06);
  const pageW = c.width - margin * 2;
  const pageH = c.height - margin * 2;
  fillRect(c, margin, margin, pageW, pageH, PAPER);

  const pad = Math.round(pageW * 0.07);
  const left = margin + pad;
  const usableW = pageW - pad * 2;
  let y = margin + pad;

  // Header block — a few heavy rules, as every BOL and rate confirmation has.
  fillRect(c, left, y, Math.round(usableW * 0.55), 26, INK);
  y += 46;
  fillRect(c, left, y, usableW, 4, INK);
  y += 28;

  const lineHeight = density === "dense" ? 22 : 40;
  const glyphH = density === "dense" ? 11 : 15;
  const bottom = margin + pageH - pad;

  while (y + lineHeight < bottom) {
    // A line of words: runs of ink with gaps, jittered so the page is not a perfect grating (a
    // perfect grating has a pathological Laplacian response and would flatter every blur metric).
    let x = left;
    const lineEnd = left + usableW * (density === "dense" ? 1 : 0.62);
    while (x < lineEnd) {
      const wordW = Math.round(28 + random() * 76);
      const gap = Math.round(8 + random() * 10);
      if (x + wordW > lineEnd) break;
      for (let gx = x; gx < x + wordW; gx += 4) fillRect(c, gx, y, 3, glyphH, INK);
      x += wordW + gap;
    }
    y += lineHeight;
  }

  if (marks) {
    // A red inspector's stamp and a blue signature. These exist so the corpus can hold the Phase 6.1
    // rule — enhancement must not flatten meaningful colour — to something measurable, and so the
    // RGB-to-luminance step (D-SCAN2) is exercised by pixels that are not already grey.
    const sx = margin + Math.round(pageW * 0.58);
    const sy = margin + Math.round(pageH * 0.72);
    for (let t = 0; t < 7; t++) {
      fillRect(c, sx + t, sy + t, Math.round(pageW * 0.3) - t * 2, 3, STAMP_RED);
      fillRect(c, sx + t, sy + Math.round(pageH * 0.1) - t, Math.round(pageW * 0.3) - t * 2, 3, STAMP_RED);
    }
    fillRect(c, sx, sy, 3, Math.round(pageH * 0.1), STAMP_RED);
    fillRect(c, sx + Math.round(pageW * 0.3), sy, 3, Math.round(pageH * 0.1), STAMP_RED);

    const gy = margin + Math.round(pageH * 0.88);
    for (let i = 0; i < Math.round(pageW * 0.34); i++) {
      const gx = margin + pad + i;
      const wobble = Math.round(Math.sin(i / 13) * 16 + Math.sin(i / 4.1) * 5);
      fillRect(c, gx, gy + wobble, 2, 5, PEN_BLUE);
    }
  }
  return c;
}

// ── effects ─────────────────────────────────────────────────────────────────────────────────────

/** Separable box blur, `passes` times. Three passes approximate a gaussian closely enough. */
function blur(c, radiusX, radiusY, passes = 3) {
  for (let p = 0; p < passes; p++) {
    if (radiusX > 0) c.rgb = boxPass(c.rgb, c.width, c.height, radiusX, true);
    if (radiusY > 0) c.rgb = boxPass(c.rgb, c.width, c.height, radiusY, false);
  }
  return c;
}

function boxPass(src, width, height, radius, horizontal) {
  const out = Buffer.alloc(src.length);
  const outer = horizontal ? height : width;
  const inner = horizontal ? width : height;
  for (let o = 0; o < outer; o++) {
    for (let ch = 0; ch < 3; ch++) {
      let sum = 0;
      let count = 0;
      const at = (i) => ((horizontal ? o * width + i : i * width + o) * 3 + ch);
      for (let i = -radius; i <= radius; i++) {
        if (i >= 0 && i < inner) {
          sum += src[at(i)];
          count++;
        }
      }
      for (let i = 0; i < inner; i++) {
        out[at(i)] = Math.round(sum / count);
        const drop = i - radius;
        const add = i + radius + 1;
        if (drop >= 0) {
          sum -= src[at(drop)];
          count--;
        }
        if (add < inner) {
          sum += src[at(add)];
          count++;
        }
      }
    }
  }
  return out;
}

/** Multiplicative left-to-right illumination gradient — a window or a cab light off one shoulder. */
function sideLight(c, from, to) {
  return mapPixels(c, (r, g, b, x) => {
    const k = from + (to - from) * (x / (c.width - 1));
    return [r * k, g * k, b * k];
  });
}

/** A soft elliptical darkening — the driver's own hand or phone between the light and the page. */
function shadow(c, cx, cy, rx, ry, strength) {
  return mapPixels(c, (r, g, b, x, y) => {
    const d = ((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2;
    if (d >= 1) return [r, g, b];
    const k = 1 - strength * (1 - d) ** 1.5;
    return [r * k, g * k, b * k];
  });
}

/** An additive specular highlight — gloss, a sleeve, a windscreen reflection. Clips at 255. */
function specular(c, cx, cy, rx, ry, gain) {
  return mapPixels(c, (r, g, b, x, y) => {
    const d = ((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2;
    if (d >= 1) return [r, g, b];
    const add = gain * (1 - d) ** 0.6;
    return [r + add, g + add, b + add];
  });
}

/** Pull every value toward mid grey — a flat, washed-out capture. */
function lowContrast(c, keep) {
  return mapPixels(c, (r, g, b) => [128 + (r - 128) * keep, 128 + (g - 128) * keep, 128 + (b - 128) * keep]);
}

/** Scale exposure up or down without touching contrast shape. */
function exposure(c, k) {
  return mapPixels(c, (r, g, b) => [r * k, g * k, b * k]);
}

/** Several overlapping illumination lobes — a page that is not lying flat. */
function crumple(c, seed) {
  const random = rng(seed);
  const lobes = Array.from({ length: 5 }, () => ({
    cx: random() * c.width,
    cy: random() * c.height,
    rx: c.width * (0.25 + random() * 0.3),
    ry: c.height * (0.2 + random() * 0.3),
    k: 0.82 + random() * 0.3,
  }));
  return mapPixels(c, (r, g, b, x, y) => {
    let k = 1;
    for (const l of lobes) {
      const d = ((x - l.cx) / l.rx) ** 2 + ((y - l.cy) / l.ry) ** 2;
      if (d < 1) k *= 1 + (l.k - 1) * (1 - d);
    }
    return [r * k, g * k, b * k];
  });
}

// ── the corpus ──────────────────────────────────────────────────────────────────────────────────
const DESK = [188, 185, 178];
const SEAT = [46, 44, 48];

/**
 * Each entry names the condition it encodes, so a reader picking a fixture out of a failure message
 * knows what it was for without opening it. `axes` is machine-read by the test that proves the corpus
 * still covers everything the plan says it covers.
 */
const CORPUS = [
  { name: "clean-sharp-even-portrait-dense", axes: { sharpness: "sharp", lighting: "even", glare: "none", contrast: "high", orientation: "portrait", density: "dense" }, build: (c, s) => drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }) },
  { name: "clean-sharp-even-landscape-dense", axes: { sharpness: "sharp", lighting: "even", glare: "none", contrast: "high", orientation: "landscape", density: "dense" }, landscape: true, build: (c, s) => drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }) },
  { name: "clean-sharp-even-portrait-sparse", axes: { sharpness: "sharp", lighting: "even", glare: "none", contrast: "high", orientation: "portrait", density: "sparse" }, build: (c, s) => drawPage(c, { surface: DESK, density: "sparse", marks: false, seed: s }) },
  { name: "soft-mild-portrait-dense", axes: { sharpness: "soft", lighting: "even", glare: "none", contrast: "high", orientation: "portrait", density: "dense" }, build: (c, s) => blur(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), 1, 1, 1) },
  { name: "soft-heavy-portrait-dense", axes: { sharpness: "soft", lighting: "even", glare: "none", contrast: "high", orientation: "portrait", density: "dense" }, build: (c, s) => blur(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), 4, 4, 2) },
  { name: "motion-blur-portrait-dense", axes: { sharpness: "motion", lighting: "even", glare: "none", contrast: "high", orientation: "portrait", density: "dense" }, build: (c, s) => blur(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), 9, 0, 1) },
  { name: "sidelit-mild-portrait-dense", axes: { sharpness: "sharp", lighting: "side", glare: "none", contrast: "high", orientation: "portrait", density: "dense" }, build: (c, s) => sideLight(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), 1.05, 0.72) },
  { name: "sidelit-strong-portrait-dense", axes: { sharpness: "sharp", lighting: "side", glare: "none", contrast: "high", orientation: "portrait", density: "dense" }, build: (c, s) => sideLight(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), 1.12, 0.4) },
  { name: "hand-shadow-portrait-dense", axes: { sharpness: "sharp", lighting: "shadow", glare: "none", contrast: "high", orientation: "portrait", density: "dense" }, build: (c, s) => shadow(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), c.width * 0.3, c.height * 0.42, c.width * 0.42, c.height * 0.3, 0.45) },
  { name: "phone-shadow-landscape-dense", axes: { sharpness: "sharp", lighting: "shadow", glare: "none", contrast: "high", orientation: "landscape", density: "dense" }, landscape: true, build: (c, s) => shadow(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), c.width * 0.62, c.height * 0.55, c.width * 0.3, c.height * 0.5, 0.5) },
  { name: "specular-patch-portrait-dense", axes: { sharpness: "sharp", lighting: "even", glare: "patch", contrast: "high", orientation: "portrait", density: "dense" }, build: (c, s) => specular(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), c.width * 0.62, c.height * 0.34, c.width * 0.16, c.height * 0.11, 120) },
  { name: "specular-strip-landscape-dense", axes: { sharpness: "sharp", lighting: "even", glare: "patch", contrast: "high", orientation: "landscape", density: "dense" }, landscape: true, build: (c, s) => specular(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), c.width * 0.5, c.height * 0.3, c.width * 0.45, c.height * 0.07, 140) },
  { name: "blown-highlight-portrait-dense", axes: { sharpness: "sharp", lighting: "even", glare: "blown", contrast: "high", orientation: "portrait", density: "dense" }, build: (c, s) => specular(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), c.width * 0.5, c.height * 0.45, c.width * 0.3, c.height * 0.22, 210) },
  { name: "blown-half-portrait-dense", axes: { sharpness: "sharp", lighting: "even", glare: "blown", contrast: "high", orientation: "portrait", density: "dense" }, build: (c, s) => specular(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), c.width * 0.5, c.height * 0.4, c.width * 0.62, c.height * 0.45, 240) },
  { name: "low-contrast-portrait-dense", axes: { sharpness: "sharp", lighting: "even", glare: "none", contrast: "low", orientation: "portrait", density: "dense" }, build: (c, s) => lowContrast(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), 0.42) },
  { name: "low-contrast-dim-portrait-dense", axes: { sharpness: "sharp", lighting: "even", glare: "none", contrast: "low", orientation: "portrait", density: "dense" }, build: (c, s) => exposure(lowContrast(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), 0.35), 0.72) },
  { name: "underexposed-portrait-dense", axes: { sharpness: "sharp", lighting: "even", glare: "none", contrast: "high", orientation: "portrait", density: "dense" }, build: (c, s) => exposure(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), 0.42) },
  { name: "overexposed-portrait-dense", axes: { sharpness: "sharp", lighting: "even", glare: "blown", contrast: "low", orientation: "portrait", density: "dense" }, build: (c, s) => exposure(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), 1.35) },
  { name: "colour-marks-sharp-portrait-dense", axes: { sharpness: "sharp", lighting: "even", glare: "none", contrast: "high", orientation: "portrait", density: "dense", colour: true }, build: (c, s) => drawPage(c, { surface: DESK, density: "dense", marks: true, seed: s }) },
  { name: "colour-marks-lowlight-portrait-dense", axes: { sharpness: "sharp", lighting: "even", glare: "none", contrast: "low", orientation: "portrait", density: "dense", colour: true }, build: (c, s) => exposure(drawPage(c, { surface: DESK, density: "dense", marks: true, seed: s }), 0.55) },
  { name: "dark-background-portrait-dense", axes: { sharpness: "sharp", lighting: "even", glare: "none", contrast: "high", orientation: "portrait", density: "dense", background: "dark" }, build: (c, s) => drawPage(c, { surface: SEAT, density: "dense", marks: false, seed: s }) },
  { name: "cab-dim-soft-portrait-dense", axes: { sharpness: "soft", lighting: "side", glare: "none", contrast: "low", orientation: "portrait", density: "dense", background: "dark" }, build: (c, s) => blur(sideLight(exposure(drawPage(c, { surface: SEAT, density: "dense", marks: true, seed: s }), 0.6), 1.1, 0.55), 3, 3) },
  { name: "windscreen-glare-sidelit-landscape-dense", axes: { sharpness: "sharp", lighting: "side", glare: "patch", contrast: "high", orientation: "landscape", density: "dense" }, landscape: true, build: (c, s) => specular(sideLight(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), 1.15, 0.6), c.width * 0.3, c.height * 0.4, c.width * 0.25, c.height * 0.3, 165) },
  { name: "crumpled-illumination-portrait-dense", axes: { sharpness: "sharp", lighting: "uneven", glare: "none", contrast: "high", orientation: "portrait", density: "dense" }, build: (c, s) => crumple(drawPage(c, { surface: DESK, density: "dense", marks: false, seed: s }), s + 991) },
];

function render(entry, index) {
  const size = entry.landscape ? LANDSCAPE : PORTRAIT;
  const c = canvas(size.width, size.height, DESK);
  entry.build(c, 1000 + index * 37);
  return c;
}

function pixelDigest(rgb) {
  return createHash("sha256").update(rgb).digest("hex");
}

function build() {
  return CORPUS.map((entry, index) => {
    const c = render(entry, index);
    return {
      entry,
      canvas: c,
      record: {
        name: entry.name,
        file: `${entry.name}.png`,
        width: c.width,
        height: c.height,
        axes: entry.axes,
        pixelSha256: pixelDigest(c.rgb),
      },
    };
  });
}

const built = build();
const manifest = {
  // Bumped whenever the generator changes what it draws, so a stale checkout says so out loud rather
  // than reporting 24 mysterious digest mismatches.
  corpusVersion: "scanner-fixtures-1",
  note: "Generated by fixtures/generate.mjs. Digests are over raw RGB pixels, not file bytes — see that file's header.",
  fixtures: built.map((b) => b.record),
};

if (process.argv.includes("--check")) {
  const onDisk = JSON.parse(readFileSync(join(HERE, "manifest.json"), "utf8"));
  const drift = [];
  if (onDisk.corpusVersion !== manifest.corpusVersion) {
    drift.push(`corpusVersion: manifest says ${onDisk.corpusVersion}, generator says ${manifest.corpusVersion}`);
  }
  const byName = new Map(onDisk.fixtures.map((f) => [f.name, f]));
  for (const record of manifest.fixtures) {
    const previous = byName.get(record.name);
    if (!previous) drift.push(`${record.name}: absent from manifest.json`);
    else if (previous.pixelSha256 !== record.pixelSha256) drift.push(`${record.name}: pixels changed`);
    byName.delete(record.name);
  }
  for (const orphan of byName.keys()) drift.push(`${orphan}: in manifest.json but no longer generated`);

  if (drift.length > 0) {
    console.error("✗ fixture corpus drifted from manifest.json:\n" + drift.map((d) => `  ${d}`).join("\n"));
    console.error("\n  If the change was intended: bump corpusVersion, rerun `node fixtures/generate.mjs`,");
    console.error("  and say in the commit what moved and why — every metric baseline downstream shifts with it.");
    process.exit(1);
  }
  console.log(`✓ fixture corpus matches manifest.json (${manifest.fixtures.length} fixtures)`);
} else {
  for (const b of built) {
    writeFileSync(join(HERE, b.record.file), encodePng(b.canvas.rgb, b.canvas.width, b.canvas.height));
  }
  writeFileSync(join(HERE, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
  console.log(`✓ wrote ${manifest.fixtures.length} fixtures + manifest.json`);
}
