import type { IconSvgElement } from '@hugeicons/react-native';
import {
  AccountSettingIcon,
  ActivityIcon,
  Alert02Icon,
  ArrowDownIcon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUpIcon,
  BadgeCheckIcon,
  BadgeIcon,
  BoltIcon,
  Calendar01Icon,
  CameraAdd01Icon,
  CameraIcon,
  Cancel01Icon,
  CancelCircleIcon,
  CheckIcon,
  CheckmarkCircleIcon,
  CheckmarkSquareIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CloudAlertIcon,
  CloudCheckIcon,
  CloudOffIcon,
  CloudSyncIcon,
  CompassIcon,
  CopyIcon,
  CreditCardIcon,
  DangerIcon,
  Delete02Icon,
  Directions01Icon,
  Download01Icon,
  DropletsIcon,
  EyeIcon,
  EyeOffIcon,
  FilterIcon,
  FireIcon,
  FlashIcon,
  FuelStationIcon,
  HealthIcon,
  HelpCircleIcon,
  HistoryIcon,
  Home01Icon,
  HourglassIcon,
  InformationCircleIcon,
  Image01Icon,
  LocationIcon,
  Login01Icon,
  Logout01Icon,
  LockIcon,
  Mail01Icon,
  MapPinIcon,
  MapPinXIcon,
  MapsIcon,
  MedalFirstPlaceIcon,
  Menu01Icon,
  MoneyIcon,
  Moon02Icon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  NavigationIcon,
  Notification01Icon,
  Notification02Icon,
  OilBarrelIcon,
  PaymentIcon,
  PencilEdit01Icon,
  PlayCircleIcon,
  PlayIcon,
  QrCodeScanIcon,
  RadioButtonIcon,
  Refresh01Icon,
  RouteIcon,
  SchoolIcon,
  Search01Icon,
  Settings01Icon,
  ShieldIcon,
  StarAwardIcon,
  StarIcon,
  SunIcon,
  TaskDoneIcon,
  TruckIcon,
  Upload01Icon,
  UserCircleIcon,
  UserIcon,
  Wifi01Icon,
  WifiOffIcon,
} from '@hugeicons/core-free-icons';
import type { MaterialSymbolName } from './materialSymbols.generated';

// Semantic icon names stay stable for screens while the visual library is HugeIcons. This keeps
// product vocabulary independent from vendor-specific icon names and makes future icon updates a
// single-adapter change rather than a screen-by-screen migration.
export const HUGE_ICONS: Record<MaterialSymbolName, IconSvgElement> = {
  account_circle: UserCircleIcon,
  add: AccountSettingIcon,
  add_a_photo: CameraAdd01Icon,
  arrow_back: ArrowLeft01Icon,
  arrow_forward: ArrowRight01Icon,
  attach_money: MoneyIcon,
  badge: BadgeIcon,
  bolt: BoltIcon,
  calendar_today: Calendar01Icon,
  call: Notification01Icon,
  cancel: Cancel01Icon,
  check: CheckIcon,
  check_box: CheckmarkSquareIcon,
  check_box_outline_blank: CheckmarkSquareIcon,
  check_circle: CheckmarkCircleIcon,
  chevron_left: ChevronLeftIcon,
  chevron_right: ChevronRightIcon,
  close: Cancel01Icon,
  cloud_done: CloudCheckIcon,
  cloud_off: CloudOffIcon,
  cloud_sync: CloudSyncIcon,
  content_copy: CopyIcon,
  credit_card: CreditCardIcon,
  dangerous: DangerIcon,
  dark_mode: Moon02Icon,
  delete: Delete02Icon,
  directions: Directions01Icon,
  do_not_disturb_on: CancelCircleIcon,
  done: CheckIcon,
  download: Download01Icon,
  edit: PencilEdit01Icon,
  error: Alert02Icon,
  ev_station: FuelStationIcon,
  event: Calendar01Icon,
  expand_less: ChevronUpIcon,
  expand_more: ChevronDownIcon,
  explore: CompassIcon,
  filter_list: FilterIcon,
  flash_on: FlashIcon,
  fmd_bad: MapPinXIcon,
  health_and_safety: HealthIcon,
  help: HelpCircleIcon,
  history: HistoryIcon,
  home: Home01Icon,
  hourglass_empty: HourglassIcon,
  image: Image01Icon,
  info: InformationCircleIcon,
  keyboard_arrow_down: ChevronDownIcon,
  keyboard_arrow_up: ChevronUpIcon,
  light_mode: SunIcon,
  local_fire_department: FireIcon,
  local_gas_station: FuelStationIcon,
  local_shipping: TruckIcon,
  lock: LockIcon,
  lock_open: LockIcon,
  login: Login01Icon,
  logout: Logout01Icon,
  mail: Mail01Icon,
  map: MapsIcon,
  menu: Menu01Icon,
  military_tech: MedalFirstPlaceIcon,
  more_horiz: MoreHorizontalIcon,
  more_vert: MoreVerticalIcon,
  my_location: LocationIcon,
  navigation: NavigationIcon,
  north: ArrowUpIcon,
  notifications: Notification01Icon,
  notifications_active: Notification02Icon,
  oil_barrel: OilBarrelIcon,
  open_in_new: ArrowRight01Icon,
  payments: PaymentIcon,
  pending: HourglassIcon,
  person: UserIcon,
  photo_camera: CameraIcon,
  pin_drop: MapPinIcon,
  place: LocationIcon,
  play_arrow: PlayIcon,
  play_circle: PlayCircleIcon,
  priority_high: Alert02Icon,
  qr_code_scanner: QrCodeScanIcon,
  quiz: HelpCircleIcon,
  radio_button_checked: RadioButtonIcon,
  radio_button_unchecked: RadioButtonIcon,
  refresh: Refresh01Icon,
  remove: Cancel01Icon,
  report: Alert02Icon,
  route: RouteIcon,
  schedule: HourglassIcon,
  school: SchoolIcon,
  science: ActivityIcon,
  search: Search01Icon,
  settings: Settings01Icon,
  shield: ShieldIcon,
  signal_cellular_off: WifiOffIcon,
  south: ArrowDownIcon,
  speed: ActivityIcon,
  star: StarIcon,
  sync: Refresh01Icon,
  sync_problem: CloudAlertIcon,
  task_alt: TaskDoneIcon,
  trending_down: ArrowDownIcon,
  trending_up: ArrowUpIcon,
  upload: Upload01Icon,
  verified: BadgeCheckIcon,
  verified_user: ShieldIcon,
  visibility: EyeIcon,
  visibility_off: EyeOffIcon,
  warning: Alert02Icon,
  water_drop: DropletsIcon,
  wifi: Wifi01Icon,
  wifi_off: WifiOffIcon,
  workspace_premium: StarAwardIcon,
};
