import CoreGraphics
import CryptoKit
import Foundation
import ImageIO

/**
 The iOS half of D-SCAN9: hold `CaptureMetrics.swift` to `fixtures/expected.json`.

 ── WHY THIS IS AN EXECUTABLE AND NOT AN XCTEST ───────────────────────────────────────────────
 The plan's Step 3.1 asks for "an XCTest reading the Step 0.3 fixtures from the bundle". A bundle
 means an app target, an app target means a simulator, and `apps/driver/ios` is generated by
 `expo prebuild` and gitignored (`apps/driver/.gitignore:4`) — so an Xcode test target added there
 would be erased by the next `--clean` prebuild and would exist in nobody else's checkout. The thing
 being tested is pure arithmetic over a byte array with no iOS dependency at all, so it needs none of
 that: `swiftc` compiles the SAME `CaptureMetrics.swift` the module ships, for macOS, and runs it
 against the same corpus in about a second. That is a deviation from the step text and it is recorded
 in the plan's §8 log rather than quietly taken.

 What it therefore does NOT cover, stated so nobody mistakes a green run for more than it is:
 whether `measure()` is reachable across the Expo bridge, and whether `UIImage` on a real device
 hands `CaptureImageDecode` the same pixels ImageIO hands it here. Both are on the device-session
 agenda (D-SCAN13).

 ── TWO TOLERANCES, BECAUSE ONE OF THEM CANNOT SEE A TYPO ─────────────────────────────────────
 `expected.json` declares ±2% on blur and ±0.002 on the fractions. Those were written before any
 native implementation existed (plan §6 Q3 says so in as many words), and measuring them on
 2026-09-07 found them about four orders of magnitude looser than the actual noise: a correct
 transliteration reproduces the whole corpus to 0.00026% and 5.0e-7, and both of those figures are
 nothing but the rounding `expected.mjs` applies when it commits the file. The arithmetic agrees
 EXACTLY, because it is integer arithmetic on both sides.

 A tolerance four orders too wide is a tolerance that passes real bugs, and two were demonstrated:
 changing the Rec.709 green coefficient from 46871 to 46870, and replacing the box-downscale's
 rounding with truncation (1.78% on blur — under the 2% line). Both PASSED.

 So this harness checks twice. The declared tolerance stays the cross-platform CONTRACT and is
 checked first. Then each deviation is checked against what the baseline's own rounding can account
 for — half a unit in the last committed place, derived from `tolerance.baselineDecimals` rather than
 written here — and anything above that fails as EXACT. Both mutations above then fail. Widening the
 declared tolerance to make a run green remains forbidden; this is the opposite move, and it is
 reported separately so that "iOS disagrees with the reference" and "iOS is no longer bit-exact with
 the reference" never arrive as the same sentence.

 ── THE TWO FAILURES IT KEEPS APART ───────────────────────────────────────────────────────────
 A tolerance miss can mean "Swift computes the metric differently" or "Swift is measuring different
 pixels". Those are unrelated bugs, and one pass/fail would hide which you had. So every fixture is
 checked in two stages: first the decoded RGB is digested and compared against the corpus's own
 `pixelSha256` — which `generate.mjs` computed over the pixels it wrote, before any PNG existed —
 and only then are the numbers compared. A decode mismatch says DECODE in those words and skips the
 arithmetic entirely, because a tolerance verdict on the wrong pixels means nothing at all.

 Usage: `./run-metrics-parity.sh` (which passes the fixtures directory as the only argument).
 */
@main
enum MetricsParity {
  static func main() {
    let arguments = CommandLine.arguments
    guard arguments.count >= 2 else { fail("usage: metrics-parity <fixtures-dir>") }
    let fixturesDirectory = URL(fileURLWithPath: arguments[1], isDirectory: true)

    guard let expectedData = try? Data(contentsOf: fixturesDirectory.appendingPathComponent("expected.json")),
          let root = (try? JSONSerialization.jsonObject(with: expectedData)) as? [String: Any],
          let tolerance = root["tolerance"] as? [String: Any],
          let blurRelativeTolerance = tolerance["blurVarianceRelative"] as? Double,
          let fractionTolerance = tolerance["fractionAbsolute"] as? Double,
          let baselineDecimals = tolerance["baselineDecimals"] as? [String: Int],
          let blurDecimals = baselineDecimals["blurVariance"],
          let fractionDecimals = baselineDecimals["fraction"],
          let analysisLongEdgePx = root["analysisLongEdgePx"] as? Int,
          let fixtures = root["fixtures"] as? [[String: Any]]
    else {
      fail("could not read expected.json under \(fixturesDirectory.path)")
    }

    print("metrics-parity · iOS · \(root["metricsVersion"] as? String ?? "?") / "
      + "\(root["corpusVersion"] as? String ?? "?") · analysis scale \(analysisLongEdgePx) px")
    // Half a unit in the last committed place: the most `expected.mjs`'s own rounding can move a
    // value. Anything beyond it is the implementation, not the file format.
    let blurExactBound = 0.5 * pow(10.0, -Double(blurDecimals))
    let fractionExactBound = 0.5 * pow(10.0, -Double(fractionDecimals))

    print(String(format: "contract tolerance: blur ±%.1f%% relative, fractions ±%.4f absolute",
                 blurRelativeTolerance * 100, fractionTolerance))
    print(String(format: "exactness bound:    blur ±%g absolute, fractions ±%g absolute "
                 + "(half the last committed place: %d / %d decimals)",
                 blurExactBound, fractionExactBound, blurDecimals, fractionDecimals))
    print("")

    var worst = Worst()
    var failures: [String] = []
    var decodeFailures = 0

    for fixture in fixtures {
      guard let name = fixture["name"] as? String,
            let expectedWidth = fixture["width"] as? Int,
            let expectedHeight = fixture["height"] as? Int,
            let pixelSha256 = fixture["pixelSha256"] as? String,
            let expected = fixture["metrics"] as? [String: Any]
      else {
        fail("malformed fixture record in expected.json")
      }

      // The file is the fixture name plus `.png`, which is what the corpus manifest records.
      // Deriving it rather than opening manifest.json keeps this harness reading ONE file — the
      // property `expected.mjs` deliberately arranged when it copied the digest across.
      let url = fixturesDirectory.appendingPathComponent(name + ".png")
      guard let source = CGImageSourceCreateWithURL(url as CFURL, nil),
            let image = CGImageSourceCreateImageAtIndex(source, 0, nil),
            let decoded = CaptureImageDecode.decode(image)
      else {
        failures.append("\(name): DECODE could not read \(url.lastPathComponent)")
        decodeFailures += 1
        continue
      }

      if decoded.width != expectedWidth || decoded.height != expectedHeight {
        failures.append("\(name): DECODE size \(decoded.width)x\(decoded.height), "
          + "expected \(expectedWidth)x\(expectedHeight)")
        decodeFailures += 1
        continue
      }
      let digest = rgbDigest(decoded)
      if digest != pixelSha256 {
        failures.append("\(name): DECODE pixels differ — sha256 \(digest.prefix(12))…, "
          + "expected \(pixelSha256.prefix(12))…")
        decodeFailures += 1
        continue
      }

      guard let measured = CaptureMetrics.compute(
        rgb: decoded.rgba,
        width: decoded.width,
        height: decoded.height,
        analysisLongEdgePx: analysisLongEdgePx,
        channels: CaptureImageDecode.channels
      ) else {
        failures.append("\(name): CaptureMetrics.compute returned nil")
        continue
      }

      var failed = false

      for (metric, actual) in [("longEdgePx", measured.longEdgePx),
                               ("analysisLongEdgePx", measured.analysisLongEdgePx)] {
        let want = expected[metric] as? Int ?? -1
        if actual != want {
          failures.append("\(name): \(metric) \(actual), expected \(want)")
          failed = true
        }
      }

      let expectedBlur = (expected["blurVariance"] as? Double) ?? Double.nan
      let blurDelta = abs(measured.blurVariance - expectedBlur)
      let blurRelative = expectedBlur == 0 ? blurDelta : blurDelta / abs(expectedBlur)
      worst.noteBlur(relative: blurRelative, absolute: blurDelta, name)
      if !(blurRelative <= blurRelativeTolerance) {
        failures.append(String(format: "%@: blurVariance %.4f, expected %.4f (%.3f%% off)",
                               name, measured.blurVariance, expectedBlur, blurRelative * 100))
        failed = true
      } else if !(blurDelta <= blurExactBound) {
        failures.append(String(format: "%@: EXACT blurVariance %.6f, expected %.4f (Δ%.6f > %g)",
                               name, measured.blurVariance, expectedBlur, blurDelta, blurExactBound))
        failed = true
      }

      for (metric, actual) in [("glareFraction", measured.glareFraction),
                               ("brightnessMean", measured.brightnessMean),
                               ("contrastRms", measured.contrastRms),
                               ("shadowRange", measured.shadowRange)] {
        let want = (expected[metric] as? Double) ?? Double.nan
        let delta = abs(actual - want)
        worst.noteFraction(delta, metric, name)
        // Written as `!(delta <= t)` rather than `delta > t` so that a NaN — which every comparison
        // answers false to — fails instead of passing. A missing key in expected.json would
        // otherwise read as agreement.
        if !(delta <= fractionTolerance) {
          failures.append(String(format: "%@: %@ %.6f, expected %.6f (Δ%.6f)", name, metric, actual, want, delta))
          failed = true
        } else if !(delta <= fractionExactBound) {
          failures.append(String(format: "%@: EXACT %@ %.9f, expected %.6f (Δ%.9f > %g)",
                                 name, metric, actual, want, delta, fractionExactBound))
          failed = true
        }
      }

      print(pad(name, 44)
        + String(format: "blur %11.4f (%.4f%% off)", measured.blurVariance, blurRelative * 100)
        + (failed ? "   ✗" : "   ✓"))
    }

    print("")
    print(String(format: "worst blur deviation:     %.5f%% relative (%@) · %.6f absolute (%@)",
                 worst.blurRelative * 100, worst.blurFixture, worst.blurAbsolute, worst.blurAbsoluteFixture))
    print(String(format: "worst fraction deviation: %.9f absolute (%@ on %@)",
                 worst.fractionAbsolute, worst.fractionName, worst.fractionFixture))
    print(String(format: "headroom: %.0f× on the contract tolerance, %.1f× on the exactness bound",
                 blurRelativeTolerance / max(worst.blurRelative, 1e-12),
                 blurExactBound / max(worst.blurAbsolute, 1e-12)))
    print("")

    if failures.isEmpty {
      print("RESULT: PASS — \(fixtures.count) fixtures, iOS reproduces the reference exactly "
        + "(every deviation explained by the baseline's own rounding)")
      exit(0)
    }
    for message in failures { print("  ✗ \(message)") }
    print("")
    if decodeFailures > 0 {
      print("\(decodeFailures) of these are DECODE failures: Swift measured different pixels, so its")
      print("arithmetic was never compared. Fix the decode before reading anything into the numbers.")
    }
    print("RESULT: FAIL — \(failures.count) problem(s) across \(fixtures.count) fixtures")
    exit(1)
  }

  /// The worst deviation seen anywhere in the corpus, so that a green run still reports a
  /// MEASUREMENT. §6 Q3 asks whether these tolerances are right; "everything passed" does not answer
  /// it, and the standing rule is that a tolerance is never widened to make a run green — so the only
  /// useful thing a passing run can say is how much headroom there actually was.
  private struct Worst {
    var blurRelative = 0.0
    var blurFixture = "—"
    var blurAbsolute = 0.0
    var blurAbsoluteFixture = "—"
    var fractionAbsolute = 0.0
    var fractionName = "—"
    var fractionFixture = "—"

    mutating func noteBlur(relative: Double, absolute: Double, _ fixture: String) {
      if relative > blurRelative { blurRelative = relative; blurFixture = fixture }
      if absolute > blurAbsolute { blurAbsolute = absolute; blurAbsoluteFixture = fixture }
    }

    mutating func noteFraction(_ value: Double, _ metric: String, _ fixture: String) {
      if value > fractionAbsolute {
        fractionAbsolute = value
        fractionName = metric
        fractionFixture = fixture
      }
    }
  }

  /// The corpus digests RAW RGB — three bytes per pixel, tightly packed — because deflate output can
  /// differ across zlib versions while every pixel is unchanged. So the alpha channel this decoder
  /// produces is dropped before hashing, rather than the digest being redefined to suit the decoder.
  private static func rgbDigest(_ decoded: CaptureImageDecode.Decoded) -> String {
    var rgb = [UInt8]()
    rgb.reserveCapacity(decoded.width * decoded.height * 3)
    var p = 0
    while p + 3 <= decoded.rgba.count {
      rgb.append(decoded.rgba[p])
      rgb.append(decoded.rgba[p + 1])
      rgb.append(decoded.rgba[p + 2])
      p += 4
    }
    return SHA256.hash(data: rgb).map { String(format: "%02x", $0) }.joined()
  }

  private static func pad(_ text: String, _ width: Int) -> String {
    text.count >= width ? text + " " : text + String(repeating: " ", count: width - text.count)
  }

  private static func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data(("✗ " + message + "\n").utf8))
    exit(2)
  }
}
